// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iortbbfukmfwbtuhepde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvcnRiYmZ1a21md2J0dWhlcGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjY5MDksImV4cCI6MjA2MTQ0MjkwOX0.gR4UIYT9N7fcuQ4Y3LQm4mpD34o5goQ3PPyEqlyl2qQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);